// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagementApp.Data;

#nullable disable

namespace OrderManagementApp.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("delivery_date");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("order_number");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerEmail")
                        .IsUnique();

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6629),
                            CustomerEmail = "user1@test.com",
                            CustomerName = "User Test 1",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0001",
                            ProductId = 2,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6629)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6673),
                            CustomerEmail = "user2@test.com",
                            CustomerName = "User Test 2",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0002",
                            ProductId = 3,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6673)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6679),
                            CustomerEmail = "user3@test.com",
                            CustomerName = "User Test 3",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0003",
                            ProductId = 4,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6679)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6684),
                            CustomerEmail = "user4@test.com",
                            CustomerName = "User Test 4",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0004",
                            ProductId = 5,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6685)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6689),
                            CustomerEmail = "user5@test.com",
                            CustomerName = "User Test 5",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0005",
                            ProductId = 6,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6690)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6694),
                            CustomerEmail = "user6@test.com",
                            CustomerName = "User Test 6",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0006",
                            ProductId = 7,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6695)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6699),
                            CustomerEmail = "user7@test.com",
                            CustomerName = "User Test 7",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0007",
                            ProductId = 8,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6699)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6703),
                            CustomerEmail = "user8@test.com",
                            CustomerName = "User Test 8",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0008",
                            ProductId = 9,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6704)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6708),
                            CustomerEmail = "user9@test.com",
                            CustomerName = "User Test 9",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0009",
                            ProductId = 10,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6708)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6713),
                            CustomerEmail = "user10@test.com",
                            CustomerName = "User Test 10",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0010",
                            ProductId = 11,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6713)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6718),
                            CustomerEmail = "user11@test.com",
                            CustomerName = "User Test 11",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0011",
                            ProductId = 12,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6718)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6723),
                            CustomerEmail = "user12@test.com",
                            CustomerName = "User Test 12",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0012",
                            ProductId = 13,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6723)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6728),
                            CustomerEmail = "user13@test.com",
                            CustomerName = "User Test 13",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0013",
                            ProductId = 14,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6728)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6732),
                            CustomerEmail = "user14@test.com",
                            CustomerName = "User Test 14",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0014",
                            ProductId = 15,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6733)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6737),
                            CustomerEmail = "user15@test.com",
                            CustomerName = "User Test 15",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0015",
                            ProductId = 1,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6737)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6741),
                            CustomerEmail = "user16@test.com",
                            CustomerName = "User Test 16",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0016",
                            ProductId = 2,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6741)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6745),
                            CustomerEmail = "user17@test.com",
                            CustomerName = "User Test 17",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0017",
                            ProductId = 3,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6746)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6750),
                            CustomerEmail = "user18@test.com",
                            CustomerName = "User Test 18",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0018",
                            ProductId = 4,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6750)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6754),
                            CustomerEmail = "user19@test.com",
                            CustomerName = "User Test 19",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0019",
                            ProductId = 5,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6754)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6759),
                            CustomerEmail = "user20@test.com",
                            CustomerName = "User Test 20",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0020",
                            ProductId = 6,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6759)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6763),
                            CustomerEmail = "user21@test.com",
                            CustomerName = "User Test 21",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0021",
                            ProductId = 7,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6763)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6768),
                            CustomerEmail = "user22@test.com",
                            CustomerName = "User Test 22",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0022",
                            ProductId = 8,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6768)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6772),
                            CustomerEmail = "user23@test.com",
                            CustomerName = "User Test 23",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0023",
                            ProductId = 9,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6772)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6776),
                            CustomerEmail = "user24@test.com",
                            CustomerName = "User Test 24",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0024",
                            ProductId = 10,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6777)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6781),
                            CustomerEmail = "user25@test.com",
                            CustomerName = "User Test 25",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0025",
                            ProductId = 11,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6781)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6785),
                            CustomerEmail = "user26@test.com",
                            CustomerName = "User Test 26",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0026",
                            ProductId = 12,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6785)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6789),
                            CustomerEmail = "user27@test.com",
                            CustomerName = "User Test 27",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0027",
                            ProductId = 13,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6790)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6794),
                            CustomerEmail = "user28@test.com",
                            CustomerName = "User Test 28",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0028",
                            ProductId = 14,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6794)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6798),
                            CustomerEmail = "user29@test.com",
                            CustomerName = "User Test 29",
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0029",
                            ProductId = 15,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6798)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6802),
                            CustomerEmail = "user30@test.com",
                            CustomerName = "User Test 30",
                            DeliveryDate = new DateTime(2025, 12, 31, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderDate = new DateTime(2025, 12, 28, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6563),
                            OrderNumber = "ORD-20251228-0030",
                            ProductId = 1,
                            Quantity = 1,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6803)
                        });
                });

            modelBuilder.Entity("OrderManagementApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6400),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 1",
                            Price = 1010m,
                            Sku = "IPHONE-15-001",
                            StockQuantity = 51,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6401)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6405),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 2",
                            Price = 1020m,
                            Sku = "IPHONE-15-002",
                            StockQuantity = 52,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6406)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6410),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 3",
                            Price = 1030m,
                            Sku = "IPHONE-15-003",
                            StockQuantity = 53,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6410)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6414),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 4",
                            Price = 1040m,
                            Sku = "IPHONE-15-004",
                            StockQuantity = 54,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6414)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6417),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 5",
                            Price = 1050m,
                            Sku = "IPHONE-15-005",
                            StockQuantity = 55,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6417)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6420),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 6",
                            Price = 1060m,
                            Sku = "IPHONE-15-006",
                            StockQuantity = 56,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6420)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6423),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 7",
                            Price = 1070m,
                            Sku = "IPHONE-15-007",
                            StockQuantity = 57,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6423)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6426),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 8",
                            Price = 1080m,
                            Sku = "IPHONE-15-008",
                            StockQuantity = 58,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6426)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6429),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 9",
                            Price = 1090m,
                            Sku = "IPHONE-15-009",
                            StockQuantity = 59,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6429)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6434),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 10",
                            Price = 1100m,
                            Sku = "IPHONE-15-010",
                            StockQuantity = 60,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6435)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6438),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 11",
                            Price = 1110m,
                            Sku = "IPHONE-15-011",
                            StockQuantity = 61,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6438)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6441),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 12",
                            Price = 1120m,
                            Sku = "IPHONE-15-012",
                            StockQuantity = 62,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6441)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6444),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 13",
                            Price = 1130m,
                            Sku = "IPHONE-15-013",
                            StockQuantity = 63,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6444)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6446),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 14",
                            Price = 1140m,
                            Sku = "IPHONE-15-014",
                            StockQuantity = 64,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6447)
                        },
                        new
                        {
                            Id = 15,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6449),
                            Description = "High-end smartphone",
                            Name = "IPhone 15 Pro Max Version 15",
                            Price = 1150m,
                            Sku = "IPHONE-15-015",
                            StockQuantity = 65,
                            UpdatedAt = new DateTime(2026, 1, 17, 15, 37, 9, 497, DateTimeKind.Local).AddTicks(6449)
                        });
                });

            modelBuilder.Entity("OrderManagementApp.Models.Order", b =>
                {
                    b.HasOne("OrderManagementApp.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagementApp.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
